cc_library (
	name = "Output",
	deps = [
		"Format",
		"Mode"
	],
    visibility = ["//src:__pkg__", "//test:__pkg__"]
)

cc_library (
    name = "Format",
    srcs = ["Format.cc"],
    hdrs = ["Format.h"],
)

cc_library (
    name = "Mode",
    srcs = ["Mode.cc"],
    hdrs = ["Mode.h"],
)
