cc_library (
	name = "File",
	deps = [
		"_File",
		"Filter"
	],
	visibility = ["//src:__pkg__"]
)

cc_library (
    name = "_File",
    srcs = ["File.cc"],
    hdrs = ["File.h"],
)

cc_library (
    name = "Filter",
    srcs = ["Filter.cc"],
    hdrs = ["Filter.h"],
)
