cc_library (
	name = "Misc",
	deps = [
		"Config",
		"Preprocess",
		"ShellComp"
	],
	visibility = ["//src:__pkg__"]
)

cc_library (
    name = "Config",
    srcs = ["Config.cc"],
    hdrs = ["Config.h"],
)

cc_library (
    name = "Preprocess",
    srcs = ["Preprocess.cc"],
    hdrs = ["Preprocess.h"],
)

cc_library (
    name = "ShellComp",
    srcs = ["ShellComp.cc"],
    hdrs = ["ShellComp.h"],
)
