cc_library (
	name = "Regex",
	deps = [
		"Engine",
		"Mmap",
		"Reader"
	],
	visibility = ["//src:__pkg__"]
)

cc_library (
    name = "Engine",
    srcs = ["Engine.cc"],
    hdrs = ["Engine.h"],
)

cc_library (
    name = "Mmap",
    srcs = ["Mmap.cc"],
    hdrs = ["Mmap.h"],
)

cc_library (
    name = "Reader",
    srcs = ["Reader.cc"],
    hdrs = ["Reader.h"],
)
