cc_binary (
    name = "bomo",
	srcs = ['main.cc'],
    deps = [
        "//src/lib/Misc:Misc",
        "//src/lib/Regex:Regex",
        "//src/lib/File:File",
        "//src/lib/Thread:Thread",
        "//src/lib/Output:Output",
        "@boost.filesystem"
    ]
)
