cc_library (
    name = "Thread",
    deps = [
        "_Thread"
    ],
    visibility = ["//visibility:public"]
)

cc_library (
    name = "_Thread",
    srcs = ["Thread.cc"],
    hdrs = ["Thread.h"],
    copts = [
        "-Isrc/lib",
        "--std=c++23"
    ],
    visibility = ["//visibility:public"]
)
