cc_library (
	name = "Thread",
	deps = [
		"_Thread"
	],
    visibility = ["//src:__pkg__", "//test:__pkg__"]
)

cc_library (
    name = "_Thread",
    srcs = ["Thread.cc"],
    hdrs = ["Thread.h"],
)
